### PR TITLE
Fix for edge directions in getH3UnidirectionalEdgeBoundary

### LINKED ISSUE #75: Edge direction in getH3UnidirectionalEdgeBoundary is inconsistent
This may not be a big deal for most consumers, but the algorithm used for `getH3UnidirectionalEdgeBoundary` produces 5 edges that follow the direction of the origin's geo boundary output, and one edge that goes in the opposite direction (from the origin's vertex 5 to vertex 0).

Given that we might rewrite that algorithm to something more efficient in any case, it would be a useful requirement for the output that all edges follow consistent directionality.

### PR DESCRIPTION
**Pull request by nrabinowitz**
Fixes #75. This isn't the most elegant fix, but it does get the vertices into the correct order.

Longer term, I think the best option here is to do what we do in `h3SetToVertexGraph`, getting the edges and then walking them. But at the moment this was a bit too clunky to implement; it might be easier after a refactor of the `VertexGraph` structure.

### CODE REVIEW

File: src/apps/testapps/testH3UniEdge.c [hunk 1]
```diff
@@ -208,34 +209,113 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
...
-    H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(sf, edges);
 
-    GeoBoundary gb;
-    for (int i = 0; i < 6; i++) {
-        H3_EXPORT(getH3UnidirectionalEdgeBoundary)(edges[i], &gb);
-        t_assert(gb.numVerts == 2, "Got the expected number of vertices back");
+    int expectedVertices[][2] = {{3, 4}, {1, 2}, {2, 3},
+                                 {5, 0}, {4, 5}, {0, 1}};
+
+    for (int res = 0; res < 13; res++) {
```
Comment (nrabinowitz) [inline src/apps/testapps/testH3UniEdge.c]: Note that the current approach fails at res > 12 because of the geo comparison precision.

File: src/h3lib/lib/h3UniEdge.c [hunk 2]
```diff
@@ -212,6 +213,15 @@ void H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(H3Index origin,
     }
 }
 
+bool _hasMatchingVertex(GeoCoord* vertex, GeoBoundary* boundary) {
```
Comment (isaacbrodsky) [inline src/h3lib/lib/h3UniEdge.c]: These arguments should be const.

File: src/h3lib/lib/h3UniEdge.c [hunk 3]
```diff
@@ -229,14 +241,26 @@ void H3_EXPORT(getH3UnidirectionalEdgeBoundary)(H3Index edge, GeoBoundary* gb) {
...
-            if (geoAlmostEqualThreshold(&origin.verts[i], &destination.verts[j],
-                                        0.000001)) {
-                gb->verts[k].lat = origin.verts[i].lat;
-                gb->verts[k].lon = origin.verts[i].lon;
+        if (_hasMatchingVertex(&origin.verts[i], &destination)) {
+            // If we are on vertex 0, we need to handle the case where it's the
+            // end of the edge, not the beginning.
+            // TODO: This is fine for this limited case, but it might be
+            // better/cleaner to use a VertexGraph for this
+            printf("%d, %d\n", i,
```
Comment (isaacbrodsky) [inline src/h3lib/lib/h3UniEdge.c]: Please delete debugging statement

File: src/h3lib/lib/h3UniEdge.c [hunk 4]
```diff
@@ -229,14 +241,26 @@ void H3_EXPORT(getH3UnidirectionalEdgeBoundary)(H3Index edge, GeoBoundary* gb) {
...
+                !_hasMatchingVertex(&origin.verts[i + 1], &destination)) {
+                postponedVertex = origin.verts[i];
+            } else {
+                gb->verts[k] = origin.verts[i];
                 k++;
             }
         }
     }
+    // If we postponed adding the last vertex, add it now
+    if (postponedVertex.lat && postponedVertex.lon) {
```
Comment (isaacbrodsky) [inline src/h3lib/lib/h3UniEdge.c]: This doesn't look safe, since (0,0) is a valid set of coordinates.

File: src/h3lib/lib/h3UniEdge.c (hunk 2 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: Will update.

File: src/h3lib/lib/h3UniEdge.c (hunk 3 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: Oh, sorry. Will delete.

File: src/h3lib/lib/h3UniEdge.c (hunk 4 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: True. Is there a better option here? The only thing I can think of is to add an additional var like `hasPostponedVertex`, which is pretty ugly.

File: src/apps/testapps/testH3UniEdge.c (hunk 1 above)
Comment (isaachier) [reply src/apps/testapps/testH3UniEdge.c]: Might be worth adding as a comment.

File: src/apps/testapps/testH3UniEdge.c [hunk 5]
```diff
@@ -208,34 +209,113 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
 }
 
 TEST(getH3UnidirectionalEdgeBoundary) {
-    H3Index sf = H3_EXPORT(geoToH3)(&sfGeo, 9);
+    H3Index sf;
+    GeoBoundary boundary;
+    GeoBoundary edgeBoundary;
     H3Index* edges = calloc(6, sizeof(H3Index));
```
Comment (isaachier) [inline src/apps/testapps/testH3UniEdge.c]: Somewhat outside of your changeset, but why is `calloc` here instead of `STACK_ARRAY_CALLOC` (https://github.com/uber/h3/blob/master/src/h3lib/include/stackAlloc.h#L29)?

File: src/apps/testapps/testH3UniEdge.c [hunk 6]
```diff
@@ -208,34 +209,113 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
...
-    H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(sf, edges);
 
-    GeoBoundary gb;
-    for (int i = 0; i < 6; i++) {
-        H3_EXPORT(getH3UnidirectionalEdgeBoundary)(edges[i], &gb);
-        t_assert(gb.numVerts == 2, "Got the expected number of vertices back");
+    int expectedVertices[][2] = {{3, 4}, {1, 2}, {2, 3},
+                                 {5, 0}, {4, 5}, {0, 1}};
```
Comment (isaachier) [inline src/apps/testapps/testH3UniEdge.c]: `const`?

File: src/apps/testapps/testH3UniEdge.c [hunk 7]
```diff
@@ -208,34 +209,113 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
...
-    int missingEdgeCount = 0;
-    for (int i = 0; i < 6; i++) {
-        if (edges[i] == 0) {
-            missingEdgeCount++;
-        } else {
-            H3_EXPORT(getH3UnidirectionalEdgeBoundary)(edges[i], &gb);
-            t_assert(gb.numVerts == 3,
-                     "Got the expected number of vertices back for a Class III "
-                     "pentagon");
+    int expectedVertices[][3] = {{-1, -1, -1}, {2, 3, 4}, {4, 5, 6},
```
Comment (isaachier) [inline src/apps/testapps/testH3UniEdge.c]: `const`?

File: src/apps/testapps/testH3UniEdge.c [hunk 8]
```diff
@@ -208,34 +209,113 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
...
+}
 
-    H3Index pentagon = 0x811c0ffffffffff;
-    edges = calloc(6, sizeof(H3Index));
-    H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(pentagon, edges);
+TEST(getH3UnidirectionalEdgeBoundaryPentagonClassIII) {
+    H3Index pentagon;
+    GeoBoundary boundary;
+    GeoBoundary edgeBoundary;
+    H3Index* edges = calloc(6, sizeof(H3Index));
```
Comment (isaachier) [inline src/apps/testapps/testH3UniEdge.c]: Same stack allocation question.

File: src/apps/testapps/testH3UniEdge.c [hunk 9]
```diff
@@ -208,34 +209,113 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
...
+        H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(sf, edges);
+
+        for (int i = 0; i < 6; i++) {
+            H3_EXPORT(getH3UnidirectionalEdgeBoundary)(edges[i], &edgeBoundary);
+            t_assert(edgeBoundary.numVerts == 2,
+                     "Got the expected number of vertices back");
+            for (int j = 0; j < edgeBoundary.numVerts; j++) {
+                t_assert(
+                    geoAlmostEqual(&edgeBoundary.verts[j],
+                                   &boundary.verts[expectedVertices[i][j]]),
```
Comment (isaachier) [inline src/apps/testapps/testH3UniEdge.c]: I'm too tired to figure this out at the moment. Looks fun :).

File: src/h3lib/lib/h3UniEdge.c [hunk 10]
```diff
@@ -212,6 +213,15 @@ void H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(H3Index origin,
     }
 }
 
+bool _hasMatchingVertex(const GeoCoord* vertex, const GeoBoundary* boundary) {
```
Comment (isaachier) [inline src/h3lib/lib/h3UniEdge.c]: `static`?

File: src/h3lib/lib/h3UniEdge.c [hunk 11]
```diff
@@ -229,14 +242,25 @@ void H3_EXPORT(getH3UnidirectionalEdgeBoundary)(H3Index edge, GeoBoundary* gb) {
...
-        for (int j = 0; j < destination.numVerts; j++) {
-            if (geoAlmostEqualThreshold(&origin.verts[i], &destination.verts[j],
-                                        0.000001)) {
-                gb->verts[k].lat = origin.verts[i].lat;
-                gb->verts[k].lon = origin.verts[i].lon;
+        if (_hasMatchingVertex(&origin.verts[i], &destination)) {
+            // If we are on vertex 0, we need to handle the case where it's the
+            // end of the edge, not the beginning.
+            // TODO: This is fine for this limited case, but it might be
+            // better/cleaner to use a VertexGraph for this
```
Comment (isaachier) [inline src/h3lib/lib/h3UniEdge.c]: You are better off avoiding allocations involved in creating a `VertexGraph` and hacking a solution with only the given inputs.

File: src/h3lib/lib/h3UniEdge.c [hunk 12]
```diff
@@ -229,14 +242,25 @@ void H3_EXPORT(getH3UnidirectionalEdgeBoundary)(H3Index edge, GeoBoundary* gb) {
...
+            if (i == 0 &&
+                !_hasMatchingVertex(&origin.verts[i + 1], &destination)) {
+                postponedVertex = origin.verts[i];
+                hasPostponedVertex = true;
```
Comment (isaachier) [inline src/h3lib/lib/h3UniEdge.c]: Is zero a valid vertex? If not, you can just check that `postponedVertex != 0` instead of maintaining a separate flag.

File: src/h3lib/lib/h3UniEdge.c [hunk 13]
```diff
@@ -229,14 +242,25 @@ void H3_EXPORT(getH3UnidirectionalEdgeBoundary)(H3Index edge, GeoBoundary* gb) {
...
         }
     }
+    // If we postponed adding the last vertex, add it now
+    if (hasPostponedVertex) {
+        gb->verts[k] = postponedVertex;
+        k++;
+    }
     gb->numVerts = k;
-}
+}
```
Comment (isaachier) [inline src/h3lib/lib/h3UniEdge.c]: Deleted newline from end of file. Put a little marker here to show me.

File: src/apps/testapps/testH3UniEdge.c (hunk 1 above)
Comment (nrabinowitz) [reply src/apps/testapps/testH3UniEdge.c]: Will do.

File: src/apps/testapps/testH3UniEdge.c (hunk 5 above)
Comment (nrabinowitz) [reply src/apps/testapps/testH3UniEdge.c]: Mostly likely because this was written before we introduced that. Will update.

File: src/apps/testapps/testH3UniEdge.c (hunk 6 above)
Comment (nrabinowitz) [reply src/apps/testapps/testH3UniEdge.c]: Will add.

File: src/apps/testapps/testH3UniEdge.c (hunk 7 above)
Comment (nrabinowitz) [reply src/apps/testapps/testH3UniEdge.c]: Will add.

File: src/h3lib/lib/h3UniEdge.c (hunk 11 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: Yeah, probably true. It just irks me slightly that this is basically the same thing we're doing in `h3SetToVertexGraph` but we're doing it totally differently :/. Also bothers me that this is `O(n^2)`, even though `n` is guaranteed to be <= 10 and is usually 6. I'll drop the comment though, I doubt there'd be any benefit.

File: src/h3lib/lib/h3UniEdge.c (hunk 12 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: `postponedVertex` is a `GeoCoord` struct, and unfortunately, as @isaacbrodsky points out, it's valid to have all the fields in the struct initialized to `0`. So I don't know of another way to check whether `postponedVertex` has been set or not, hence the flag. Open to suggestions.

File: src/h3lib/lib/h3UniEdge.c (hunk 13 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: Hm. I'm surprised `clang-format` doesn't have some sort of opinion on that. Will fix.

File: src/h3lib/lib/h3UniEdge.c (hunk 10 above)
Comment (nrabinowitz) [reply src/h3lib/lib/h3UniEdge.c]: Will update.

File: src/apps/testapps/testH3UniEdge.c [hunk 14]
```diff
@@ -32,7 +33,7 @@ BEGIN_TESTS(h3UniEdge);
 
 TEST(h3IndexesAreNeighbors) {
     H3Index sf = H3_EXPORT(geoToH3)(&sfGeo, 9);
-    H3Index* ring = calloc(H3_EXPORT(maxKringSize)(1), sizeof(H3Index));
+    STACK_ARRAY_CALLOC(H3Index, ring, H3_EXPORT(maxKringSize)(1));
```
Comment (isaachier) [inline src/apps/testapps/testH3UniEdge.c]: 👍

File: src/h3lib/lib/h3UniEdge.c [hunk 15]
```diff
@@ -213,7 +213,14 @@ void H3_EXPORT(getH3UnidirectionalEdgesFromHexagon)(H3Index origin,
...
 }
 
-bool _hasMatchingVertex(const GeoCoord* vertex, const GeoBoundary* boundary) {
+/**
+ * Whether the given coordinate has a matching vertex in the given geo boundary.
+ * @param  vertex   Coordinate to check
+ * @param  boundary Geo boundary to look in
+ * @return          Whether a match was found
+ */
+static bool _hasMatchingVertex(const GeoCoord* vertex,
```
Comment (isaachier) [inline src/h3lib/lib/h3UniEdge.c]: Great!

File: src/apps/testapps/testH3UniEdge.c (hunk 6 above)
Comment (isaachier) [reply src/apps/testapps/testH3UniEdge.c]: Waiting on this when you have a chance.

File: src/apps/testapps/testH3UniEdge.c (hunk 7 above)
Comment (nrabinowitz) [reply src/apps/testapps/testH3UniEdge.c]: Added, that's what I get for trying to multitask.

File: src/apps/testapps/testH3UniEdge.c [hunk 16]
```diff
@@ -196,47 +194,118 @@ TEST(getH3UnidirectionalEdgesFromHexagon) {
...
+TEST(getH3UnidirectionalEdgeBoundaryPentagonClassIII) {
+    H3Index pentagon;
+    GeoBoundary boundary;
+    GeoBoundary edgeBoundary;
+    STACK_ARRAY_CALLOC(H3Index, edges, 6);
+
+    const int expectedVertices[][3] = {{-1, -1, -1}, {2, 3, 4}, {4, 5, 6},
+                                 {8, 9, 0},    {6, 7, 8}, {0, 1, 2}};
+
+    for (int res = 1; res < 13; res += 2) {
```
Comment (isaacbrodsky) [inline src/apps/testapps/testH3UniEdge.c]: Please add comments for why we don't test all resolutions.

**Comment by isaachier** [comment]
It seems Travis CI wants you to format the code.

**Comment by nrabinowitz** [comment]
Yeah, having more trouble with this than expected due to laptop theft :(. Should update shortly.
